import os
import base64
import io
import numpy as np
import cv2
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from PIL import Image

app = FastAPI(title="Furnishing AI Precise Drape API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class DrapeRequest(BaseModel):
    background: str  # base64
    objects: List[str]  # list of base64 patterns
    mode: str = "bedsheet"

def decode_image(b64_str: str):
    if "," in b64_str:
        b64_str = b64_str.split(",")[1]
    img_data = base64.b64decode(b64_str)
    img_np = np.frombuffer(img_data, dtype=np.uint8)
    return cv2.imdecode(img_np, cv2.IMREAD_COLOR)

def encode_image(img_np):
    _, buffer = cv2.imencode('.jpg', img_np, [int(cv2.IMWRITE_JPEG_QUALITY), 95])
    return base64.b64encode(buffer).decode('utf-8')

from mobile_sam import sam_model_registry, SamPredictor
import torch

# Load Mobile-SAM Model (Extremely Lightweight: ~40MB)
# Fits perfectly within Render's 512MB RAM limit
SAM_CHECKPOINT = "mobile_sam.pt"
MODEL_TYPE = "vit_t"
device = "cpu"

def download_model():
    if not os.path.exists(SAM_CHECKPOINT):
        print("Downloading Mobile-SAM (40MB)...")
        # Direct link to the official mobile-sam checkpoint
        url = "https://github.com/ChaoningZhang/MobileSAM/raw/master/weights/mobile_sam.pt"
        import urllib.request
        opener = urllib.request.build_opener()
        opener.addheaders = [('User-agent', 'Mozilla/5.0')]
        urllib.request.install_opener(opener)
        urllib.request.urlretrieve(url, SAM_CHECKPOINT)
        print("Download complete.")

download_model()
print("Loading Mobile-SAM into RAM...")
sam = sam_model_registry[MODEL_TYPE](checkpoint=SAM_CHECKPOINT)
sam.to(device=device)
sam.eval()
predictor = SamPredictor(sam)
print("Mobile-SAM loaded successfully!")

def get_mask_sam(image_np, input_point, input_label):
    predictor.set_image(image_np)
    masks, scores, logits = predictor.predict(
        point_coords=np.array([input_point]),
        point_labels=np.array([input_label]),
        multimask_output=True,
    )
    # Pick the mask with highest score
    return masks[np.argmax(scores)]

def apply_texture(bg, pattern, mask):
    # 1. Resize pattern to fill the mask area roughly
    h, w = bg.shape[:2]
    pattern_resized = cv2.resize(pattern, (w, h), interpolation=cv2.INTER_LINEAR)
    
    # 2. Simple Alpha Blending for verified 1:1 motif flow
    # (Future: Apply Displacement mapping from Grayscale BG)
    mask_3d = np.repeat(mask[:, :, np.newaxis], 3, axis=2).astype(np.uint8) * 255
    
    # Invert mask to get the background
    bg_inv = cv2.bitwise_and(bg, bg, mask=cv2.bitwise_not(mask.astype(np.uint8)*255))
    pattern_cut = cv2.bitwise_and(pattern_resized, pattern_resized, mask=mask.astype(np.uint8)*255)
    
    return cv2.add(bg_inv, pattern_cut)

import vertexai
from vertexai.preview.vision_models import ImageGenerationModel, ImageUpscalingModel
from dotenv import load_dotenv

load_dotenv()

# Initialize Vertex AI
# Project ID from user screenshot. Region us-central1 for best availability.
PROJECT_ID = os.getenv("GOOGLE_CLOUD_PROJECT", "project-1aa829e7-d179-46d2-a03")
vertexai.init(project=PROJECT_ID, location="us-central1")

class GenerationRequest(BaseModel):
    prompt: str
    background: str  # base64
    objects: List[str]  # list of base64 patterns
    quality: str = "1K"

@app.post("/generate-imagen")
async def generate_imagen_endpoint(req: GenerationRequest):
    try:
        # 1. Load the Imagen 3 Model (Standard is $0.03)
        model = ImageGenerationModel.from_pretrained("imagegeneration@006")
        
        # 2. Decode background for context (for inpainting/edit if needed)
        # For now, we use the multimodal "Reference Image" capability of Imagen 3 if available
        # or we generate based on the prompt which already includes the details.
        
        # Note: Imagen 3 on Vertex AI API is different from Gemini AI Studio.
        # We'll use the background as a base image for an "Edit" request to preserve scene.
        base_img = Image.open(io.BytesIO(base64.b64decode(req.background.split(",")[1] if "," in req.background else req.background)))
        
        # We simulate the Gemini vision by providing the prompt and the scene.
        # For pattern transfer, inpainting is often best.
        # However, for a quick "Vertex try", we'll use the image-to-image/generation logic.
        
        response = model.generate_images(
            prompt=req.prompt,
            number_of_images=1,
            aspect_ratio="1:1", # Default, will be handled by crop/resize
            # Optionally add guidance or mask here for more precision
        )

        if not response.images:
            raise HTTPException(status_code=500, detail="No image generated by Vertex AI")

        generated_image = response.images[0]
        
        # 3. Handle Upscaling for 2K/4K
        if req.quality in ["2K", "4K"]:
            upscale_model = ImageUpscalingModel.from_pretrained("image-upscaling@001")
            # Upscale 4x to get to 4K from 1K
            upscale_response = upscale_model.upscale_image(
                image=generated_image,
                upscale_factor=4 if req.quality == "4K" else 2
            )
            generated_image = upscale_response
            
        # 4. Return as base64
        img_byte_arr = io.BytesIO()
        generated_image.save(img_byte_arr, format='JPEG')
        img_b64 = base64.b64encode(img_byte_arr.getvalue()).decode('utf-8')
        
        return {"imageUrl": f"data:image/jpeg;base64,{img_b64}"}
        
    except Exception as e:
        print(f"Vertex Error: {e}")
        raise HTTPException(status_code=500, detail=f"Vertex AI Error: {str(e)}")

@app.post("/drape")
async def drape_endpoint(req: DrapeRequest):
    try:
        bg = decode_image(req.background)
        patterns = [decode_image(obj) for obj in req.objects]
        
        if not patterns:
            raise HTTPException(status_code=400, detail="No patterns provided")

        # AUTO-SEGMENTATION:
        # For home-furnishing, center of the image is usually the bed.
        h, w = bg.shape[:2]
        center_point = [w // 2, h // 2] 
        
        # Get mask of the blanket at the center
        mask = get_mask_sam(bg, center_point, 1)
        
        # Apply pattern 1:1 using the mask
        result_img = apply_texture(bg, patterns[0], mask)
        
        return {"imageUrl": f"data:image/jpeg;base64,{encode_image(result_img)}"}
        
    except Exception as e:
        print(f"Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
